### ISSUE TITLE
Cant import Job half the time 

### ISSUE THREAD

**Issue by MintCollie** [csurfer/pypette#1]
seems to happen whenever i create a python file that has `from pypette import Job` in it and run it.

**Comment by csurfer** [comment]
Update to the latest version and let me know if you are still facing the same problem. Looks like something might be wrong with your setup. Can you post the error message it is throwing.

**Comment by csurfer** [comment]
Closing this as I haven't seen this problem anywhere else. If you are still facing this problem please create an issue with all the details you can provide about the problem.
