### ISSUE TITLE
Job dependency a little complex

### ISSUE THREAD

**Issue by liuliqiang** [csurfer/pypette#5]
@csurfer  thanks for your codes, after read the README docs, i found it's a good project.

However, i think it can be better, such as job dependency is a little complex, i have ever try [Airlfow](), it's job dependency describe is interesting, in airflow, you can define the dependency like this:

```
job1 << job2  # for job1 depend job2
job3 >> job4  # for job4 depend job3
```

maybe it can be implemented in this project. 😄

**Comment by csurfer** [comment]
@yetship What exactly did you find complex in creating the dependency? Can you provide more details please?

**Comment by csurfer** [comment]
With v0.0.9 you can add dependencies to pipelines with `add_dependency` method. That should resolve your issues.
